### ISSUE TITLE
jsstore-encrypt with webworker

### ISSUE THREAD

**Issue by jamiefraser** [ujjwalguptaofficial/jsstore-encrypt#2]
Hi - not 100% sure I'm diagnosing my own problem correctly, but here goes.

I'm building a Blazor WASM project and I'm using jsstore to work with IndexedDB.  Works nicely and I'm happy.  *However*, my customer needs the database to be encrypted and that's where I'm running into a problem.  I have to use a webworker or my data access code makes the UI janky and unusable.  However, when I use a webworker I run into all the kookiness of trying to import a module and that's where I'm stuck.  Here's where I've managed to get:

I have a project called BlazorIndexedDB (terrible name, I know).  It has all my data access code.  Inside that project I have a js file called blazorDB.js -> it is what creates the database and exposes my project specific data access API.

In blazorDB.js I have this line 

import { encryptPlugin } from '/jsstore-encrypt'; 

(at the top where you'd expect).

If I don't include the '/' or .'/' it totally chokes with

'Uncaught TypeError: Failed to resolve module specifier "jsstore-encrypt". Relative references must start with either "/", "./", or "../".'

If I add '/' to the name I get

'Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.'

*sigh*

How do I import this module properly?  I'm completely flummoxed!

**Comment by ujjwalguptaofficial** [comment]
why are using `/` in the module, its an npm module so it will be resolved with name only.

```
import { encryptPlugin } from 'jsstore-encrypt';
```
