### ISSUE TITLE
Datetime field gives the error

### ISSUE THREAD

**Issue by shaangidwani** [ujjwalguptaofficial/jsstore-encrypt#8]
1. When we try to set encrypt date-time time fields it gives the error below :

message: Invalid array length

2. When any data is null and that column is set as encrypted then it gives the error:

Cannot read properties of undefined (reading 'encrypt')

**Comment by shaangidwani** [comment]
Can anybody help on this please?

**Comment by ujjwalguptaofficial** [comment]
@shaangidwani date time field is object, so your encryption algorithm might not be working for this. I feel issue is inside the encrypt method. Please debug and check what data is being returned from your encrypt method.

**Comment by ujjwalguptaofficial** [comment]
I have also released a new version - 1.2.0 with promise fix. Please update and check.

**Comment by shaangidwani** [comment]
> @shaangidwani date time field is an object, so your encryption algorithm might not be working for this. I feel the issue is inside the encrypt method. Please debug and check what data is being returned from your encrypt method.

When the date field is set as encrypted at that time we got this error :

<img width="943" alt="image" src="https://github.com/ujjwalguptaofficial/jsstore-encrypt/assets/26000152/3391c75d-4fd6-43f3-8db4-be51e1a0cf20">

**Comment by shaangidwani** [comment]
> I have also released a new version - 1.2.0 with promise fix. Please update and check.

After updating 1.2.0 We face the same error. for the time being, we use the decrypt function once we get the data from the select query.

Ex: We got the data from a select query then we have to use the decrypt function in the loop for decrypting the data. 

For encrypting, we don't have any issues.

**Comment by shaangidwani** [comment]
When selecting the data with join table and join table having encrypted value then its not decrypted any data.
{
with: TableNames.Patients,
on: TableNames.Visits + ".PatientID=" + TableNames.Patients+".PatientID",
as: {
OLPatientID: TableNames.Visits + "_OLPatientID",
FacilityID: TableNames.Facility + "_FacilityID",
PracticeID: TableNames.Patients + "_PracticeID",

                }
            },
in the above example, if the patient table has encrypted values like first name and last name, it does not always give decrypted values.

**Comment by ujjwalguptaofficial** [comment]
please provide me something reproducible, an example repo please. I will surely help you.
